name: CI - Debug

run-name: Debug - ${{ github.ref_name || github.ref }}

on:
  workflow_dispatch: {}
  push:
    branches:
      - test

jobs:
  ci_debugger:
    runs-on:
      - X64

    steps:
      - name: Template
        run: |
          eche "Hello, world!"
          echo "This is a device running on ${{ runner.os }}!"
